# Generated by Django 4.1.7 on 2023-03-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_category_alter_ruleparamvariant_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='calendar',
            name='color_event',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='Color event'),
        ),
    ]
