# Generated by Django 4.1.7 on 2023-03-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_alter_calendar_options_alter_rule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='Europe/Vienna', max_length=40, verbose_name='time zone'),
        ),
    ]
