# Generated by Django 4.1.7 on 2023-04-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_alter_rule_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('end__gt', models.F('start'))), name='check_start_end_date_ordering'),
        ),
    ]
