# Generated by Django 4.1.7 on 2023-07-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_event_check_start_end_date_ordering'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='check_start_end_date_ordering',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('end__gte', models.F('start'))), name='check_start_end_date_ordering'),
        ),
    ]
